name: next_byte
description: Next_Byte A Video Sharing Flutter App. using Firebase and Firestore Video Hosting as Backend.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.1
  simple_circular_progress_bar: ^1.0.2
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.2.8
  get: ^4.6.6
  intl: ^0.19.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.1.3
  http: ^1.2.2
  url_launcher: ^6.3.0
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  video_player: ^2.9.2
  video_compress: ^3.1.3
  timeago: ^3.7.0
  cached_network_image: any
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  #carousel_slider:
  #shared_preferences:
  #intl_phone_number_input:
  #pinput:
  #pin_code_fields:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

#flutter_launcher_icons:
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logos/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logos/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logos/logo.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/
    - assets/videos/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
